version: "3"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - server
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=jamonto5.dis.eafit.edu.co
    depends_on:
      - mongo-server
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - frontend

